---
title: "Rapid"
author: "Anuj Dahiya"
date: "1/23/2020"
output: pdf_document
---

# Libraries

```{r}
library(readr)
library(dplyr)
library(magrittr)
library(stringr)
```

# Paths

```{r}
path = "~/GitHub/FIDE/Chess Scripts/Step 1 - Download/Rapid/"
files = list.files(path = path)
rapid_paths = paste(path, files, sep = "")

string <- c(month.abb, tolower(month.abb), toupper(month.abb), "RATING")%>%
          paste(collapse = "|")


first_line <- function(path){
  
    con <- file(path,"r")
    first_line <- readLines(con,n=1)%>%
                  str_replace("ID Nu", "ID_Nu")
    close(con)
    return(first_line)
    
}

indexes <- function(column_vector){ 
  
    indexes <- rep(0, nchar(column_vector))
    for(i in 1:nchar(column_vector)){
        index = grep("\\s[A-z]", substr(column_vector, i, i+1))
        if (identical(index, integer(0)) == TRUE){indexes[i] = 0}
        else {indexes[i] = 1}
                                    }
    return(c(0, which(indexes == 1), nchar(column_vector)))
    
}

clean <- function(x){
  x[grepl("Fed|FED|COUNTRY", x)] <- "Country"
  x[grepl("Gms|GAMES|GM|Game|GAME", x)] <- "Games"
  x[grepl("K", x)] <- "K_factor"
  x[grepl("FLAG|Flag|flag", x)] <- "Activity"
  x[x %in% c("Wtit","wtit","WTIT", "WTit")] <- "WTitle"
  x[x %in% c("TITLE","Title","title","Tit")] <- "Title"
  x[grepl(string, x)] <- "Rating"
  x[grepl("Born|Age|age|BIRTHDAY|B-day|Bday", x)] <- "Age_Birthday"
  x[grepl("SEX", x)] <- "Sex"
  x[grepl("FOA", x)] <- "FIDE_Online_Arena"
  x[grepl("OTit", x)] <- "Other_Titles"
  return(x)
}

# suppressMessages()
```



```{r}
rapid_paths%>%
sapply(first_line)%>%
sapply(indexes)%>%
sapply(diff)%>%
setNames(files)-> col_positions

rapid_paths%>%
sapply(first_line)%>%
strsplit("\\s+")%>%
lapply(clean)%>%
setNames(files) -> columns

read_fwf(rapid_paths[1], 
         col_positions = fwf_widths(col_positions[[1]]),
         skip = 1)%>%
set_colnames(columns[[1]])

```

